<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students
[<!ELEMENT students (student)*>
<!ELEMENT student (name, age, specialty, grade)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT specialty (#PCDATA)>
<!ELEMENT age (#PCDATA)>
]>
<students>
    <student>
        <name>배하늘</name>
        <age>24</age>
        <specialty>소프트웨어공학</specialty>
        <grade>4</grade>
    </student>
    <student>
        <name>이제랑</name>
        <age>22</age>
        <specialty>경영학</specialty>
        <grade>2</grade>
    </student>
</students>